### ISSUE TITLE
Accept command-line --stage option

### ISSUE THREAD

**Issue by kernwig** [ar90n/serverless-plugin-export-endpoints#2]
I expected the normal --stage (or -s) option to function with exportEndpoints. I wish each environment to write a different file, to prevent an accidental mismatch between the last deployed cloud environment and the webapp using the exported endpoints.

Running:

`sls exportEndpoints -r $AWS_REGION -s qa`

With serverless.yml including:
```
plugins:
  - serverless-plugin-export-endpoints

custom:
  exportEndpoints:
    path: "../common/api/cloud-${self:provider.stage}.json"
```

Writes the file cloud-dev.json, no matter what stage I try to set from the command-line.

Please add the command-line option.
